baseURL = "https://nasirhussain.tech/"
languageCode = "en-us"
title = "Nasir Hussain"
theme = "LeaveIt"


paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[params]
    since = 2019
    author = "Nasir Hussain"                           # Author's name
    avatar = "/images/me/avatar.jpg"           # Author's avatar
    subtitle = "FOSS & Fedora Project Advocate | Engineering Intern at Sastaticket.pk"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "Hello World" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank"> This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.</a>'

[params.social]
    GitHub = "https://github.com/nasirhm/"
    Twitter = "https://twitter.com/_dev_nasir_"
    Linkedin = "https://www.linkedin.com/in/nasirhm/"